CREATE TABLE LIVRO (
	ID_LIVRO BIGSERIAL,
	TITULO VARCHAR(64) NOT NULL,
	AUTOR VARCHAR(64) NOT NULL,
	CONSTRAINT PK_ID_LIVRO PRIMARY KEY (ID_LIVRO)
);

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR) VALUES (100, 'Test1', 'Stephen Hawking'); 
INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR) VALUES (101, 'Test2', 'Dave Eggers'); 
INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR) VALUES (102, 'Test3', 'Ishmael Beah'); 
INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR) VALUES (103, 'Test4', 'Madeleine L’Engle'); 
INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR) VALUES (104, 'Test5', 'Alice Munro'); 
INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR) VALUES (105, 'Test6', 'Kotler,Steven / Diamandis,Peter H.'); 